FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    python3-pip \
    ros-humble-rmw-cyclonedds-cpp && \
    pip3 install prometheus-client fastapi uvicorn

EXPOSE 8001

WORKDIR /rosscope
COPY collector/ ./collector/
COPY exporter/ ./exporter/
COPY main.py .

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && python3 main.py"]