FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install prometheus-client

WORKDIR /rosscope
COPY collector/ ./collector/
COPY exporter/ ./exporter/
COPY main.py .

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && python3 main.py"]
